### ISSUE TITLE
Could not setup platfrom Chargeamps sensor

### ISSUE THREAD

**Issue by Farfar** [kirei/hass-chargeamps#22]
Since last update (1.5.1) I can't get chargeamps integration to work on Home Assistant <2021.09.0
From logs:
```
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 9:39:34 AM (1 occurrences)
Last logged: 9:39:34 AM

Unable to prepare setup for platform chargeamps.sensor: Platform not found (cannot import name 'STATE_CLASS_TOTAL_INCREASING' from 'homeassistant.components.sensor' (/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/sensor/__init__.py)).
```

Add requirement in manifest for homeassistant >=2021.09.0

**Comment by jschlyter** [comment]
Fixed in 5d1113b92be8285dfd1b8ec21e52ba10eec9e21d

It seems difficult to maintain backwards compatibility :-(
